### ISSUE TITLE
configure don't run well

### ISSUE THREAD

**Issue by pierrotm777** [rlogiacco/AnalogButtons#2]
Hello,
I try to use the new version from a long time and hd now understood what is my issue!
I con't configure the buttons!

So i have just changed into your example the configure fonction like that:
void configure() {
        int val = analogRead(ANALOG_PIN);
	Serial.println(val);
	delay(1000);
}

Now , i can configure the buttons and play with !!!

**Comment by rlogiacco** [comment]
I believe I've applied your suggested fix to the master branch

**Comment by pierrotm777** [comment]
Cool thanks
