### ISSUE TITLE
Action on ButtonUp/ButtonDown

### ISSUE THREAD

**Issue by ForestCat4** [rlogiacco/AnalogButtons#4]
Not sure how difficult this would be to implement.  Consider this scenario:

A group of 5 buttons, which toggle the values of 5 elements in an array, Array1

If the 5th button is 'long-pressed', it changes the target of the 5 buttons to a different array, Array2

If Button5 is long-pressed again, it switches back to Array1.

Is there currently a way to have Button5 only change the value of the 5th array element upon release of a 'click', so that, for example, if Array1[5] = '1', a long-press of Button5 won't change it back to '0' before (or after) switching to the second array?

If not, would you consider adding that functionality?  Very useful for ui/menu type of functions.

Thanks.

EDIT:  I was able to mod the library to do this.  It's a bit of a hack, but seems to be stable.  Also removed the 'repeating hold', since it was not the functionality my project needed.  If anyone wants it, let me know.

**Comment by crisap94** [comment]
Can you explain the situation in a better way? Actually i didn't get it.

**Comment by rlogiacco** [comment]
I 'm not sure the functionality you are looking for would fit into the AnalogButtons library: you want to use one button for both a long press and a short press, with the long press not being detected as a short press. To do so you need to intercept the short press, start a timer and, unless a long press is detected, fire the short press event. Otherwise fire a long press.

What the library can do for you is giving you the possibility to execute whatever code you want both for a short press and a long press, so nobody prevents you to have the short press function do something like:

> 1. store the current millisecond
> 2. activate the short press flag

Using a matching long press function which:
> 1. clears the short press flag
> 2. do whatever your long press function should do

This can be paired with a piece of code in your looping function which:
> 1. checks if the short press flag is active and compares current time with the stored time
> 2. if long press time is passed but the flag is still active, execute the short press function

Does it make sense to you? Is this what you are looking for?

**Comment by ForestCat4** [comment]
Guys, have a look at the following analogButtons.cpp.  It does what I needed, and may better explain what I was trying to do.  my changes are annotated w/ 'nn_' at the head of the comment
NOTE:  It is quick & dirty, and I'm sure there are more elegant solutions...
*****************************************************
#include "AnalogButtons.h"
#include <Arduino.h>

/* 05/10/16 _nn Made some changes to wait until button is released before generating a "click", 
* Hold function still works on a long press, however it will no longer generate repeated "hold" events
*  while it is held or generate a "click" event upon release
*/

byte pressedNum;  // nn_ var to store pressed button# (see below)


Button::Button(uint16_t value, void (*clickFunction)(void), void (*holdFunction)(void), uint16_t holdDuration, uint16_t holdInterval) {
	this->value = value;
	this->duration = holdDuration;
	this->interval = holdInterval;
	this->clickFunction = clickFunction;
	this->holdFunction = holdFunction;
}

AnalogButtons::AnalogButtons(uint8_t pin, uint8_t mode, uint16_t debounce, uint8_t margin) {
	this->pin = pin;
	this->debounce = debounce;
	this->counter = 0;
	this->margin = margin;
	pinMode(pin, mode);
}

void AnalogButtons::add(Button button) {
	if (buttonsCount < ANALOGBUTTONS_MAX_SIZE) {
    	buttons[buttonsCount++] = button;
  	}
}

void AnalogButtons::check() {
	// In case this function gets called very frequently avoid sampling the analog pin too often: max frequency is 50Hz
	if (millis() - time > 120) {
		time = millis();
		uint16_t reading = analogRead(pin);
		for (uint8_t i = 0; i < buttonsCount; i++) {
			if (reading >= buttons[i].value - margin && reading <= buttons[i].value + margin) {
				
				if (lastButtonPressed != &buttons[i]) {
					if (++counter >= debounce) {
						lastButtonPressed = &buttons[i];
						counter = 0;
						pressedNum = i+1; //nn- to catch button pressed, adding one so I can use it as a '> 0' flag later
						// buttons[i].pressed(); // moved to below.  If here will activate on press.					
						previousMillis = millis();
					}
				} else {

					 if (buttons[i].isHeldDown != true && ((millis() - previousMillis) > buttons[i].duration)) {
						buttons[i].isHeldDown = true;
						buttons[i].held();
						pressedNum = 0; // we don't want to trigger a click
						previousMillis = millis();
					}
				}
				// The first matching button is the only one that gets triggered
				return;
			} else {

				buttons[i].isHeldDown = false;
			}
// ******** nn_ my code to act on button release ****
		if (pressedNum > 0 && reading < 50){ 
			buttons[pressedNum-1].pressed();
			pressedNum = 0; 
		}		
// **************************************************		
		}

		// If execution reaches this point then no button has been pressed during this check
		lastButtonPressed = 0;
		
	}
}

**Comment by ForestCat4** [comment]
Guys, have a look at the attached
[AnalogButtonsCPP.zip](https://github.com/rlogiacco/AnalogButtons/files/259908/AnalogButtonsCPP.zip)

  It does what I needed, and may better explain what I was trying to do. My changes are annotated w/ 'nn_' at the head of the comment
NOTE: It is quick & dirty, and I'm sure there are more elegant solutions, but it seems to be working...

**Comment by rlogiacco** [comment]
This will be fixed in the upcoming `1.2.0` release: any feedback before the release gets published is welcome
